### ISSUE TITLE
v2.2.2 tag /sources missing from GitHub

### ISSUE THREAD

**Issue by fanquake** [dmgbuild/mac_alias#23]
While it is available on PyPI: https://pypi.org/project/mac-alias/#files, there is no `2.2.2` tag / source bundle available via Github: https://github.com/dmgbuild/mac_alias/tags. Was that intentional, and users should move to downloading from PyPI, or just forgetten during the release?

**Comment by freakboy3742** [comment]
It certainly wasn't *deliberate*... and I even had the tag set locally - I just hadn't pushed it. Apologies for the inconvenience; it's there now.

In terms of whether PyPI is preferred... I'm not sure how to answer that, other than Yes. I don't think I've ever used GitHub as a source for Python packages... the fact that there is source bundle on Github is an artefact Github's design, rather than any sort of recommendation of the Python ecosystem. 

(This is, at least in part, why missing tags happen. Unless you're using Github CI to generate the packages, the fact that a tag is missing on Github has no impact on how PyPI operates, unless you're doing some deep code forensics)
